server:
  port: 9000
spring:
  application:
    name: gateway-api
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.13:8840
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: false
    sentinel:
      transport:
        dashboard: localhost:9998
      eager: false
      datasource:
        gateway-api:
          nacos:
            server-addr: 192.168.3.13:8840
            dataId: ${spring.application.name}-gateway-api
            groupId: SENTINEL_GROUP
            rule-type: gw_api_group
        gateway-flow:
          nacos:
            server-addr: 192.168.3.13:8840
            dataId: ${spring.application.name}-gateway-rules
            groupId: SENTINEL_GROUP
            rule-type: gw_flow
  profiles:
    active: details
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always



