spring:
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://order-center
          predicates:
            - Path=/order-feign-sentinel/**
        - id: product
          uri: lb://product-center
          predicates:
            - Path=/product/**
            - OwnTimeBetween=上午8:00, 下午6:20




