spring:
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://order-center
          predicates:
            - Path=/order-feign-sentinel/**
          filters:
            - AddRequestParameter=owner, gjx
        - id: product
          uri: lb://product-center
          predicates:
            - Path=/product/**
            - OwnTimeBetween=上午00:00, 下午12:59




