server:
  port: 8112
spring:
#  application:
#    name: order-center
  datasource:
    username: nacos
    password: Nacos@8848
    url: jdbc:mysql://192.168.3.13:3306/orderdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      filters: stat,wall #\u914D\u7F6E\u8FC7\u6EE4\u5668
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.13:8840
        # 不同namespace之间的服务不能调用
        #        namespace: 3aa27f85-e1e3-4652-82a8-c180dd9a02a4
        # 不同group之间的服务不能调用
        #        group: test
        cluster-name: a
        metadata:
          version: v1
    sentinel:
      transport:
        dashboard: 192.168.3.13:9998
      eager: true
      datasource:
        flow:
          nacos:
            server-addr: 192.168.3.13:8840
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            ruleType: FLOW
        degrade:
          nacos:
            server-addr: 192.168.3.13:8840
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            rule-type: DEGRADE
        system:
          nacos:
            server-addr: 192.168.3.13:8840
            dataId: ${spring.application.name}-system-rules
            groupId: SENTINEL_GROUP
            rule-type: system
        authority:
          nacos:
            server-addr: 192.168.3.13:8840
            dataId: ${spring.application.name}-authority-rules
            groupId: SENTINEL_GROUP
            rule-type: authority
        param-flow:
          nacos:
            server-addr: 192.168.3.13:8840
            dataId: ${spring.application.name}-param-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: param-flow
#        gateway-api:
#          nacos:
#            server-addr: 192.168.3.13:8840
#            dataId: ${spring.application.name}-gateway-api
#            groupId: SENTINEL_GROUP
#            rule-type: gw_api_group
#        gateway-flow:
#          nacos:
#            server-addr: 192.168.3.13:8840
#            dataId: ${spring.application.name}-gateway-rules
#            groupId: SENTINEL_GROUP
#            rule-type: gw_flow

  main:
    allow-bean-definition-overriding: true

ribbon:
  eager‐load:
    enable: true
    clients: product-center, pay-center
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false
  ReadTimeout: 1000
  ConnectTimeout: 1000

# 推荐使用该方式
product-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.own.config.rule.SameVersionAndSameClusterPriorityRule
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

pay-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule


logging:
  level:
    com:
      own:
        api: debug

feign:
  client:
    config:
      default:
        loging-level: full
      product-center:
        logging-level: full
      pay-center:
        loging-level: full
  httpclient:
    enable: true
    max‐connections: 200
    max‐connections‐per‐route: 50
  sentinel:
    enabled: true

management:
  endpoint:
    sentinel:
      web:
        exposure:
          include: '*'